config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  resources :boards

  post "boards/add_pin_to_board" => "boards#add_pin_to_board"

  get "my_pins" => "pins#my_pins"

  get "my_boards" => "boards#my_boards"

  root to: "pages#index"
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :boards
  has_attached_file :image, styles: { show: "636x360>", index: "318x180>", thumb: "106x60>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :image, attachment_presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
  end 

  def new
    @board = Board.new
  end 

  def create
    @boards = Board.all
    @board = Board.new board_params
    @board.update_attribute("user", current_user)
    @board.save!
    render 'show'
  end 

  def show
    @board = Board.find params[:id]
  end 

  def edit
    @board = Board.find params[:id]
  end 

  def update
    @board = Board.find params[:id]
    @board.update(board_params)
    redirect_to boards_path
  end 

  def destroy
    @board = Board.find params[:id]
    @board.destroy!
    redirect_to boards_path
  end 

  def my_boards
    @my_boards = Board.where(:user_id => current_user.id)
  end 

  def add_pin_to_board
    @board = Board.find params[:board]
    @pin = Pin.find params[:pin]
    @pin.boards << @board
    render 'show'
  end 

  private 

  def board_params
    params.require(:board).permit(:name, :subtitle, :user_id)
  end 

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end 

end 

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  def index
    @pins = Pin.all
  end 

  def new
    @pin = Pin.new
  end 

  def edit
    @pin = Pin.find params[:id]
  end 

  def create
    @pin = Pin.new pin_params
    @pin.update_attribute("user", current_user)
    @pin.save!
    render :show
  end 

  def show
    @pin = Pin.find params[:id]
    

  end 

  def update
    @pin = Pin.find params[:id]
    @pin.update(pin_params)
    redirect_to pins_path
  end 

  def destroy
    @pin = Pin.find params[:id]
    @pin.destroy
    redirect_to pins_path
  end

  def my_pins
    @my_pins = Pin.where(:user => current_user)
  end 

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board_form.html.erb
<%= form_for @board do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :subtitle %>
  <%= f.text_field :subtitle %><br>
  <%= f.submit "Create board" %>
<% end %> 

app/views/boards/_boards.html.erb
<div class="container">
  <div class="card-columns">
    <% @boards.each do |board| %>
    <div class="card">
      <div class="card-block">  
      <h4 class="card-title"><%= board.name %></h4>
      <p class="card-text"><%= board.subtitle %></p>
      <%= link_to "see board", board_path(board), class: "btn btn-info" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render 'board_form' %>

app/views/boards/index.html.erb
<%= render "boards" %>

app/views/boards/my_boards.html.erb
<div class="container">
  <div class="card-columns">
    <% @my_boards.each do |my_board| %>
      <div class="card">
          <div class="card-block">
            <h4 class="card-title"><%= my_board.name %></h4>
            <p class="card-text"><%= my_board.subtitle %></p>
            <%= link_to "see board", board_path(my_board), class: "btn btn-info" %>
            <%= link_to "edit board", edit_board_path(my_board), class: "btn btn-primary" %>
            <%= link_to "delete board", board_path(my_board), class: "btn btn-success", method: :delete, data: { confirm: 'Are you sure? '} %>
          </div>
      </div> 
    <% end %>
  </div>
</div>          

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'board_form' %>

app/views/boards/show.html.erb
<div class="container">
  <div class="demo-card">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title"><%= @board.name %></h4>
        <p class="card-text"><%= @board.subtitle %></p>
        <% @board.pins.each do |pin| %>
          <%= image_tag pin.image.url(:thumb) %> 
        <% end %>  
      </div>  
      <div class="card-block">  
        <% if current_user == @board.user %>
          <%= link_to "edit board", edit_board_path(@board), class: "btn btn-success" %>
          <%= link_to "delete board", board_path(@board), class: "btn btn-info", method: :delete, data: { confirm: 'Are you sure? '} %>
          <%= link_to 'see my boards', my_boards_path, class: 'btn btn-warning' %>
        <% end %>
        <%= link_to "see all boards", boards_path, class: "btn btn-primary" %>
      </div>  
    </div>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thingz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-light bg-faded">
    <%= link_to 'Thingz', root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'All Pins', pins_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nav-item active">
          <%= link_to 'All Boards', boards_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nav-item active">
          <%= link_to 'My Pins', my_pins_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nav-item active">
          <%= link_to 'My Boards', my_boards_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>  
        <li class="nav-item pull-xs-right btn btn-warning">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nav-item pull-xs-right btn btn-danger">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
      <% else %>
        <li class="nav-item pull-xs-right btn btn-warning">
          <%= link_to 'Log In', new_user_session_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>   
        <li class="nav-item pull-xs-right btn btn-danger">
          <%= link_to 'Register here', new_user_registration_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>  
      <% end %>
    </ul>
  </nav>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Welcome to thingz</h1>

      <% if user_signed_in? %>
        <p>Click <%= link_to 'here', new_pin_path %> to create a new pin</p>
        <p>Click <%= link_to 'here', new_board_path %> to create a new board</p>
      <% else %>
        <p>Please log in or register above to get started</p>    
      <% end %>


  </div>
</div>

app/views/pins/_edit_pin.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: @pin.title %>
    <%= f.label :description %>
    <%= f.text_field :description, placeholder: @pin.title %>
    <%= f.file_field :image %>
    <%= f.submit 'submit corrections' %>
  <% end %>

app/views/pins/_new_pin_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <%= f.submit "Create pin" %>
<% end %> 

app/views/pins/edit.html.erb
<h1>Edit your pin below</h1>

  <%= render 'edit_pin' %>

  <p>Click <%= link_to 'here', pins_path %> to go back </p>

app/views/pins/index.html.erb
<div class="container">
  <div class="card-columns">
    <% @pins.each do |pin| %>
      <div class="card">
        <%= image_tag pin.image.url(:index), class: "card-img-top" %> 
          <div class="card-block">
            <h4 class="card-title"><%= pin.title %></h4>
            <p class="card-text"><%= pin.description %></p>
            <%= link_to "see pin", pin_path(pin), class: "btn btn-info" %>
          </div>
      </div> 
    <% end %>
  </div>
</div>          
       
  

app/views/pins/my_pins.html.erb
<div class="container">
  <div class="card-columns">
    <% @my_pins.each do |my_pin| %>
      <div class="card">
        <%= image_tag my_pin.image.url(:index), class: "card-img-top" %> 
          <div class="card-block">
            <h4 class="card-title"><%= my_pin.title %></h4>
            <p class="card-text"><%= my_pin.description %></p>
            <%= link_to "see pin", pin_path(my_pin), class: "btn btn-info" %>
            <%= link_to "edit pin", edit_pin_path(my_pin), class: "btn btn-primary" %>
            <%= link_to "delete pin", pin_path(my_pin), class: "btn btn-success", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
      </div> 
    <% end %>
  </div>
</div>          
       

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'new_pin_form' %>

app/views/pins/show.html.erb
<div class="container"> 
  <div class="demo-card">
    <div class="card">
        <%= image_tag @pin.image.url(:show), class: "card-img-top img-responsive" %> 
        <div class="card-block">
          <h4 class="card-title"><%= @pin.title %></h4>
            <p class="card-text"><%= @pin.description %></p>
        </div>
        <div class="card-block">
          <% if current_user == @pin.user %>
            <%= link_to "edit pin", edit_pin_path(@pin), class: "btn btn-primary" %>
            <%= link_to "delete pin", pin_path(@pin), class: "btn btn-success", method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to "see my pins", my_pins_path, class: "btn btn-warning" %>
          <% end %>
          <%= link_to 'see all pins', pins_path, class: "btn btn-info" %>
          <%= form_tag(boards_add_pin_to_board_path(pin: @pin), method: :post) do |f| %>
            <%= select_tag 'board', options_for_select(current_user.boards.collect{ |u| [u.name, u.id] }) %>
          <%= submit_tag 'submit' %>
          <% end %>  
        </div>
    </div>
  </div>
</div>